// Every agent that is not a compliance desk, in one list. The desks are
// data/compliance/agents.json; these are the rest. Every screen that names or
// counts "the agents" reads this and AGENTS, so the Overview, How it works,
// Features, Architecture and the README cannot drift apart again (they said 14,
// 15 and 16 at once before this file existed).
//
// `cadence` says when an agent runs: "morning" agents run on the book before
// anyone opens Relay and show on the Overview's "What else ran"; "on request"
// agents run when a person asks (a dossier, a policy read, a question).
import { AGENTS } from "@/lib/compliance/agents";

export interface RosterAgent {
  id: string;
  name: string;
  /** An icon name from components/icons; kept as a string so lib does not import components. */
  icon: string;
  cadence: "morning" | "on request";
  /** One sentence, in the advisor's words: what this agent is for. */
  role: string;
  reads: string;
  /** What it works out, step by step. */
  checks: string[];
  leaves: string;
  never: string;
  href: string;
  /** Whether an advisor may turn it off for themselves. Ask stays on: it is how you reach everything else. */
  canTurnOff: boolean;
  /** How it decides, in one sentence a reviewer can check against the code. */
  method: string;
  /** The rule or text it is built on. Empty when it is arithmetic or a convenience, which the card says. */
  basis: { label: string; url: string }[];
}

export const ROSTER: RosterAgent[] = [
  { id: "research", name: "Research", icon: "briefing", cadence: "morning", reads: "The client file, the service queue, the firm's record, the channels", leaves: "A briefing per household: what changed, observed, inferred with a confidence, not established", role: "Before every conversation, tells you what changed since you last spoke and what nobody has established yet.", checks: ["What changed since the last contact", "What the file observes, apart from what it only infers", "What could not be established, and why"], never: "Never contacts the client; an inference is never shown as a fact.", canTurnOff: true, href: "/research", method: "Compares the file with what it held at the last contact, and labels each item observed, inferred with a confidence, or not established.", basis: [{ label: "FINRA Rule 2090, Know Your Customer", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2090" }] },
  { id: "retrieval", name: "Retrieval", icon: "library", cadence: "morning", reads: "The document corpus, on every opportunity", leaves: "Cited passages with a reason per score, conflicts shown as conflicts, or a refusal", role: "Finds the passages in the firm's documents that support an opportunity, or refuses when none do.", checks: ["Which current documents speak to the opportunity", "How relevant each passage is, with the reasons", "Whether two documents disagree or one is past its review date"], never: "Never cites a superseded or out-of-date document, and never writes its own evidence.", canTurnOff: true, href: "/documents", method: "Searches the current documents word by word and scores each passage with the reasons; under the relevance floor it refuses rather than cite a weak match.", basis: [{ label: "FINRA Rule 2210(d)(1), content standards: fair, balanced, a sound basis", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2210" }] },
  { id: "discovery", name: "Discovery", icon: "search", cadence: "morning", reads: "What clients said, in messages, notes and contact summaries", leaves: "Candidate opportunities, each cited to its sentence", role: "Reads what clients said and spots opportunities the data feeds missed.", checks: ["Life events, money moves and intentions in messages, notes and call summaries", "How confident it is, sentence by sentence"], never: "Never puts anything on your list until you accept it.", canTurnOff: true, href: "/discovery", method: "Runs fixed extractors over what clients wrote; each candidate cites the sentence it came from and carries a confidence.", basis: [{ label: "FINRA Rule 2090, Know Your Customer", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2090" }] },
  { id: "consequence", name: "Options and consequences", icon: "hourglass", cadence: "morning", reads: "Every shelf product against the household's rules, on a copy of the household", leaves: "After-tax income, cost, access, rate risk, and the morning after, graded", role: "Shows what the morning after each option looks like before you act.", checks: ["Every product on the approved shelf against the family's rules", "After-tax income, cost, access and rate risk", "Which rules would change their verdict the next day"], never: "Never recommends; it grades every option the same way and you choose.", canTurnOff: true, href: "/simulate", method: "Applies each option to a copy of the household and runs every engine on it, so the costs and the alternatives are compared the same way.", basis: [{ label: "SEC Rule 15l-1(a)(2)(ii), care obligation: costs and reasonably available alternatives", url: "https://www.ecfr.gov/current/title-17/section-240.15l-1" }] },
  { id: "proposer", name: "Rule-change proposer", icon: "flag", cadence: "morning", reads: "Ninety days of findings", leaves: "Tighten-only rule changes with the findings behind each, for a principal", role: "Suggests stricter rules when the last 90 days of findings show a gap.", checks: ["Patterns across past findings", "Whether a change would only tighten"], never: "Never loosens a rule, and never applies a change: a principal accepts or refuses.", canTurnOff: true, href: "/compliance", method: "Counts ninety days of findings by rule and proposes a change only when it would tighten.", basis: [{ label: "FINRA Rule 3110(a), a supervisory system reasonably designed", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/3110" }] },
  { id: "meetings", name: "Meeting prep", icon: "calendar", cadence: "morning", reads: "Today's calendar and the client file behind each meeting", leaves: "A review pack and a briefing for every client meeting", role: "Builds a review pack and a briefing for every client meeting on your calendar.", checks: ["Today's calendar", "The client file behind each meeting"], never: "Never drafts anything for the client.", canTurnOff: true, href: "/meetings", method: "Reads today's calendar and assembles the file behind each client meeting into one pack.", basis: [{ label: "FINRA Rule 2090, Know Your Customer", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2090" }] },
  { id: "onboarding", name: "Onboarding", icon: "esign", cadence: "morning", reads: "Every form on every client file: when it was requested, when it was signed, and the note the team left", leaves: "Open forms escalated past the household's threshold, and a reminder drafted for each, which a person sends", role: "Keeps onboarding moving: finds every form still waiting for a signature and drafts the reminder.", checks: ["Which forms are still unsigned, and for how many days", "The escalation threshold per household: the firm's, shortened by a segment or a client", "Which have been open past that threshold and go to the branch supervisor"], never: "Never sends a reminder, never opens an account and never moves money; it prepares, and a person acts.", canTurnOff: true, href: "/onboarding", method: "Days open = today minus the day requested; past the resolved threshold it escalates, under it a reminder is drafted. Arithmetic on the file, against an illustrative procedure.", basis: [{ label: "FINRA Rule 4512, Customer Account Information", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/4512" }] },
  { id: "held-away", name: "Held-away money", icon: "custodian", cadence: "morning", reads: "What clients wrote, what the team noted, and the reason path of every opportunity, for money that is not on the platform", leaves: "Per household: each held-away signal cited to its record, the amount when one is stated, and the wallet share the file supports", role: "Finds the money each household holds elsewhere and works out your share of their wallet.", checks: ["Retirement plans at an employer, pensions, accounts at another firm, proceeds not yet arrived, equity on a vesting schedule", "The amount, when a record states one; unstated stays unstated", "Your share of the household's wealth, as a floor"], never: "Never invents a figure, never contacts the client, and never treats an outside balance as yours until it arrives.", canTurnOff: true, href: "/wallet-share", method: "Fixed patterns over the household's own records, one signal per kind, the record that states an amount preferred; wallet share is on-platform over on-platform plus the stated amounts.", basis: [{ label: "FINRA Rule 2090, Know Your Customer", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2090" }, { label: "SEC staff bulletin on account recommendations (rollovers)", url: "https://www.sec.gov/about/divisions-offices/division-trading-markets/broker-dealers/staff-bulletin-standards-conduct-broker-dealers-investment-advisers-account-recommendations-retail" }] },
  { id: "economics", name: "Book economics", icon: "chart", cadence: "morning", reads: "Every household's size and tier against the contacts, meetings, requests and open tasks on its file", leaves: "Revenue and hours per household from an illustrative schedule, and the households that pay for attention they are not getting or take hours out of proportion", role: "Shows where your hours go against where the revenue comes from, for you only.", checks: ["Estimated revenue per household, from the fee schedule by tier", "Estimated hours in the window, from the records on the file", "Who pays above the median and has gone quiet; who takes the most time for the least"], never: "Never shown to a client, never recommends dropping anyone, and never changes a fee.", canTurnOff: true, href: "/wallet-share#economics", method: "Revenue = assets times the tier's rate; hours = contacts, meetings, requests and open tasks at fixed hours each; flags are against the book's medians. Arithmetic on placeholders a firm replaces.", basis: [] },
  { id: "conversation", name: "Next conversation", icon: "voice", cadence: "morning", reads: "Held-away signals, open opportunities, unsigned forms, overdue tasks and the last contact, per household", leaves: "Who to call this week, in order, with the reason cited to its record and a draft opener you say or send", role: "Tells you who to call this week and why, so the hour goes to the client and not to working out which client.", checks: ["The one reason per household that matters most: money elsewhere, a material opportunity, an escalated form, an overdue task, or silence", "Everything else the household carries, so one call covers it", "Who is already in today's calendar"], never: "Never calls or sends; the opener is a draft, and a person makes the call.", canTurnOff: true, href: "/conversations", method: "A fixed score per kind of reason, the best per household, households already in today's calendar last. Arithmetic, not a regulation.", basis: [{ label: "FINRA Rule 2090, Know Your Customer", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2090" }] },
  { id: "ranking", name: "Ranking", icon: "settings", cadence: "morning", reads: "Every opportunity raised on the advisor's book", leaves: "Today's list: materiality times the advisor's weight, capped at the advisor's list size", role: "Orders today's list so the most material item for you is first.", checks: ["Materiality of each opportunity", "Your weight for each kind of signal", "Your list size"], never: "Never changes which options pass a family's rules; it only orders what you see.", canTurnOff: true, href: "/triage#tune", method: "Score = materiality (0 to 100) times your weight for the kind of signal; keeps the top of the list at your list size. Arithmetic, not a regulation.", basis: [] },
  { id: "dossier", name: "Dossier", icon: "crm", cadence: "on request", reads: "The file, the CRM, the captured corpus, the firm's documents, the public record", leaves: "Every claim cited, sources checked against each other, a CRM note a person files", role: "Researches one household on request and drafts the CRM note you file.", checks: ["The file, the CRM, captured messages, the firm's documents and the public record", "Where the sources disagree"], never: "Never treats the public record as fact until you confirm it.", canTurnOff: true, href: "/clients", method: "Reads five sources, checks each claim against the others and marks it corroborated, contradicted or not on file.", basis: [{ label: "FINRA Rule 2090, Know Your Customer", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/2090" }, { label: "FINRA Rule 4512, Customer Account Information", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/4512" }] },
  { id: "policy-reader", name: "Policy reader", icon: "document", cadence: "on request", reads: "A written supervisory procedure", leaves: "Candidate rules in the engine's own shape, each cited to its sentence, for a person to add to a desk", role: "Turns a written procedure into candidate rules for a desk.", checks: ["Each sentence that states an obligation", "The rule shape it maps to, cited to the sentence"], never: "Never adds a rule itself: a person chooses which to add.", canTurnOff: true, href: `/agents/${AGENTS[0].id}`, method: "Keeps sentences that carry an obligation, maps their words to facts the engines compute, and reads the number and comparator beside each.", basis: [{ label: "FINRA Rule 3110(b), written supervisory procedures", url: "https://www.finra.org/rules-guidance/rulebooks/finra-rules/3110" }] },
  { id: "ask", name: "Ask", icon: "agent", cadence: "on request", reads: "The advisor's book, the findings, the rules, the sources, today's calendar", leaves: "An answer to a plain question, with the records it read", role: "Answers a plain question from your book, the findings, the rules and the sources, with the records it read.", checks: ["Which household, desk, rule or source the question is about", "The figure from the same engine the screen uses"], never: "Never sends, and never guesses a figure it does not hold.", canTurnOff: false, href: "/", method: "Matches the question to an intent by its words; every figure comes from the same engine the screen uses, and each answer lists the records it read.", basis: [] },
];

export const MORNING = ROSTER.filter((a) => a.cadence === "morning");
export const ON_REQUEST = ROSTER.filter((a) => a.cadence === "on request");

/** Every agent: the compliance desks and the roster. */
export const AGENT_COUNT = AGENTS.length + ROSTER.length;
/** The agents that run on the book every morning, before anyone asks. */
export const MORNING_COUNT = AGENTS.length + MORNING.length;

const WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", ...["one", "two", "three", "four", "five", "six", "seven", "eight", "nine"].map((w) => `twenty-${w}`), "thirty"];
/** "Eighteen", for a sentence that starts with the count. */
export const inWords = (n: number) => (WORDS[n] ?? String(n)).replace(/^./, (x) => x.toUpperCase());
