// Bundles every record file under data/ into one generated file the app
// imports, so adding a client, an advisor or a document is one new file and
// nothing else: no import to add, no list to update.
//
// Usage: vite-node scripts/build-data.ts            write data/generated/bundle.json
//        vite-node scripts/build-data.ts -- --check  exit 1 if the bundle is stale
//
// The bundle is generated and committed, because the app is a static export
// that cannot read a directory at runtime, and the test suite must see exactly
// what the app sees. `npm run data:check` fails the build when it is stale.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("../", import.meta.url).pathname;
const OUT = join(ROOT, "data/generated/bundle.json");

function folder(name: string): unknown[] {
  const dir = join(ROOT, "data", name);
  return readdirSync(dir)
    .filter((f) => f.endsWith(".json"))
    .sort()
    .map((f) => {
      const record = JSON.parse(readFileSync(join(dir, f), "utf8")) as { id?: string };
      if (record.id !== f.replace(/\.json$/, "")) throw new Error(`data/${name}/${f}: the file name must be the record id (${record.id})`);
      return record;
    });
}

const bundle = {
  _note: "Generated by scripts/build-data.ts from data/clients, data/advisors and data/documents. Do not edit; edit the files and run npm run data:build.",
  clients: folder("clients"),
  advisors: folder("advisors"),
  documents: folder("documents"),
};
const next = JSON.stringify(bundle, null, 2) + "\n";
const check = process.argv.includes("--check");
if (check) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== next) {
    console.error("data/generated/bundle.json is stale. Run: npm run data:build");
    process.exit(1);
  }
  console.log(`bundle.json is current: ${bundle.clients.length} clients, ${bundle.advisors.length} advisors, ${bundle.documents.length} documents.`);
} else {
  writeFileSync(OUT, next);
  console.log(`Wrote data/generated/bundle.json: ${bundle.clients.length} clients, ${bundle.advisors.length} advisors, ${bundle.documents.length} documents.`);
}
